### ISSUE TITLE
Name capitalization in grunt-ng-importer affecting angular directive name

### ISSUE THREAD

**Issue by borntorun** [blessenm/ng-app-kit#1]
Trying your boilerplate I found that there is bug related with the generated directives names. Your grunt-ng-importer task is capitaliizing the first char of the file name [here](https://github.com/blessenm/grunt-ng-importer/blob/76f521505ff58108e4d126bb262d6da367137e6a/tasks/ngimporter.js#L44); But for angular directives that cause an error as they must have the first letter in lowercase [link](https://docs.angularjs.org/error/$compile/baddir).

I dont know what is the best approach: remove the capitalize and to leave the responsability of the name case to the developer (simple - I made just that on my clone when testing) or have some match for this particular case...

(good work on this boilerplate!)

**Comment by blessanm86** [comment]
Thanks for checking this out and reporting the issue. This worked perfectly when I created it. I wonder what changed. 

Well the ng-importer job is creating the import statements but I don't think thats thats the problem. The problem happens when you try to register the directive with `app.directive()`. The name used for registration is upto the user. The name comes from the function which the directive file exports.

I was previously exporting `export default function AppVersion() {}` which was failing. I modified that to be to `export default function appVersion() {}` and now it works fine. [Here is the change.](https://github.com/blessenm/ng-app-kit/commit/4c2849b3188875202658934af150bcd0d424d39f)

Im not sure if this was the fix you did in your clone. But this fix is on on the user code and not on any of the tooling files.

**Comment by borntorun** [comment]
Yes you're write: I didn´t looked very carefully to the template in ng-importer,  it is using [<%- item.importName %>.**name**](https://github.com/blessenm/grunt-ng-importer/blob/76f521505ff58108e4d126bb262d6da367137e6a/tasks/import-template.tpl#L10) to set the component name. What is being capitalized is only item.importName.
Sorry for that.

**Comment by blessanm86** [comment]
No problems. The directive function name needed to be fixed for it to work. Again thanks for reporting this issue.

There is a link to my blog post in the README.md that describes my approach. But I think you've already figured everything out. I'm closing this issue.
